# -*- coding: UTF-8 -*-
"""常量配置"""

SPIDERS = {
    "百度蜘蛛": "aidu",
    "搜狗蜘蛛": "Sogou",
    "神马蜘蛛": "Yisou",
    "头条蜘蛛": "Bytespider",
    "必应蜘蛛": "Bingbot",
    "360蜘蛛": "360Spider",
    "谷歌图片蜘蛛": "Googlebot-Image",
    "谷歌蜘蛛": "Googlebot",
    "雅虎蜘蛛": "Yahoo",
    "其它蜘蛛": "spider",
    "其他蜘蛛": "bot",
    "普通用户": "",
}

TRANS_LANG = {
    '中文': 'zh-cn',
    '英文': 'en',
    '日文': 'ja',
}

CONF_PATH = "config/config.yml"
TAG_PATH = "config/tag.yml"
IPS_PATH = "config/IPS.txt"
VERIFY_PATH = 'config/verify/'

TEM_HTML = "others/templates.html"
AD_HTML = "others/ad.html"
SITEMAP_XML = "others/sitemap.xml"
SITEMAP_TXT = "others/sitemap.txt"
ROBOTS_TXT = "others/robots.txt"
INDEX_DIR = "template/index/"
PAGE_DIR = "template/page/"
FAVICON_PATH = "static/_/image/favicon.ico"
SPIDER_LOG = "logs/spider"
CACHE_PATH = 'cache/'
CACHE_TEM_PATH = 'cache_tem/'
ACCESS_LOG_PATH = 'logs/access.log'

WEB_PATH = 'web'
TARGET_PATH = 'target'
ERRCODE_PATH = 'config/errcode.yml'
BASE_YML_PATH = 'config/base.yml'
TEM_PATH = "static/template"

MEDIA_TYPE = {".3gp": "video/3gpp",
               ".aif": "audio/x-aiff",
               ".aifc": "audio/x-aiff",
               ".aiff": "audio/x-aiff",
               ".als": "audio/X-Alpha5",
               ".asf": "video/x-ms-asf",
               ".asr": "video/x-ms-asf",
               ".asx": "video/x-ms-asf",
               ".au": "audio/basic",
               ".avi": "video/x-msvideo",
               ".awb": "audio/amr-wb",
               ".bmp": "image/bmp",
               ".cal": "image/x-cals",
               ".cmx": "image/x-cmx",
               ".cod": "image/cis-cod",
               ".dcx": "image/x-dcx",
               ".eri": "image/x-eri",
               ".es": "audio/echospeech",
               ".esl": "audio/echospeech",
               ".fh4": "image/x-freehand",
               ".fh5": "image/x-freehand",
               ".fhc": "image/x-freehand",
               ".flv": "flv-application/octet-stream",
               ".fpx": "image/x-fpx",
               ".fvi": "video/isivideo",
               ".gif": "image/gif",
               ".gz": "application/x-gzip",
               ".ico": "image/x-icon",
               ".ief": "image/ief",
               ".ifm": "image/gif",
               ".ifs": "image/ifs",
               ".imy": "audio/melody",
               ".it": "audio/x-mod",
               ".itz": "audio/x-mod",
               ".j2k": "image/j2k",
               ".jfif": "image/pipeg",
               ".jpe": "image/jpeg",
               ".jpeg": "image/jpeg",
               ".jpg": "image/jpeg",
               ".jpz": "image/jpeg",
               ".lsf": "video/x-la-asf",
               ".lsx": "video/x-la-asf",
               ".m15": "audio/x-mod",
               ".m3u": "audio/x-mpegurl",
               ".m3url": "audio/x-mpegurl",
               ".m4a": "audio/mp4a-latm",
               ".m4b": "audio/mp4a-latm",
               ".m4p": "audio/mp4a-latm",
               ".m4u": "video/vnd.mpegurl",
               ".m4v": "video/x-m4v",
               ".ma1": "audio/ma1",
               ".ma2": "audio/ma2",
               ".ma3": "audio/ma3",
               ".ma5": "audio/ma5",
               ".mdz": "audio/x-mod",
               ".mid": "audio/mid",
               ".midi": "audio/midi",
               ".mil": "image/x-cals",
               ".mio": "audio/x-mio",
               ".mng": "video/x-mng",
               ".mod": "audio/x-mod",
               ".mov": "video/quicktime",
               ".movie": "video/x-sgi-movie",
               ".mp2": "video/mpeg",
               ".mp3": "audio/mpeg",
               ".mp4": "video/mp4",
               ".mpa": "video/mpeg",
               ".mpe": "video/mpeg",
               ".mpeg": "video/mpeg",
               ".mpg": "video/mpeg",
               ".mpg4": "video/mp4",
               ".mpga": "audio/mpeg",
               ".mpv2": "video/mpeg",
               ".nbmp": "image/nbmp",
               ".nokia-op-logo": "image/vnd.nok-oplogo-color",
               ".nsnd": "audio/nsnd",
               ".ogg": "audio/ogg",
               ".pac": "audio/x-pac",
               ".pae": "audio/x-epac",
               ".pan": "application/x-pan",
               ".pbm": "image/x-portable-bitmap",
               ".pcx": "image/x-pcx",
               ".pda": "image/x-pda",
               ".pdf": "application/pdf",
               ".png": "image/png",
               ".pnm": "image/x-portable-anymap",
               ".pnz": "image/png",
               ".ppm": "image/x-portable-pixmap",
               ".pvx": "video/x-pv-pvx",
               ".qcp": "audio/vnd.qcelp",
               ".qt": "video/quicktime",
               ".qti": "image/x-quicktime",
               ".qtif": "image/x-quicktime",
               ".ra": "audio/x-pn-realaudio",
               ".ram": "audio/x-pn-realaudio",
               ".rar": "application/octet-stream",
               ".ras": "image/x-cmu-raster",
               ".rf": "image/vnd.rn-realflash",
               ".rgb": "image/x-rgb",
               ".rm": "audio/x-pn-realaudio",
               ".rmf": "audio/x-rmf",
               ".rmi": "audio/mid",
               ".rmm": "audio/x-pn-realaudio",
               ".rmvb": "audio/x-pn-realaudio",
               ".rnx": "application/vnd.rn-realplayer",
               ".roff": "application/x-troff",
               ".rp": "image/vnd.rn-realpix",
               ".rpm": "audio/x-pn-realaudio-plugin",
               ".rt": "text/vnd.rn-realtext",
               ".rte": "x-lml/x-gps",
               ".rtf": "application/rtf",
               ".rtg": "application/metastream",
               ".rtx": "text/richtext",
               ".rv": "video/vnd.rn-realvideo",
               ".rwc": "application/x-rogerwilco",
               ".s3m": "audio/x-mod",
               ".s3z": "audio/x-mod",
               ".sca": "application/x-supercard",
               ".scd": "application/x-msschedule",
               ".sct": "text/scriptlet",
               ".sdf": "application/e-score",
               ".sea": "application/x-stuffit",
               ".setpay": "application/set-payment-initiation",
               ".setreg": "application/set-registration-initiation",
               ".sgm": "text/x-sgml",
               ".sgml": "text/x-sgml",
               ".sh": "application/x-sh",
               ".shar": "application/x-shar",
               ".shtml": "magnus-internal/parsed-html",
               ".shw": "application/presentations",
               ".si6": "image/si6",
               ".si7": "image/vnd.stiwap.sis",
               ".si9": "image/vnd.lgtwap.sis",
               ".sis": "application/vnd.symbian.install",
               ".sit": "application/x-stuffit",
               ".skd": "application/x-Koan",
               ".skm": "application/x-Koan",
               ".skp": "application/x-Koan",
               ".skt": "application/x-Koan",
               ".slc": "application/x-salsa",
               ".smd": "audio/x-smd",
               ".smi": "application/smil",
               ".smil": "application/smil",
               ".smp": "application/studiom",
               ".smz": "audio/x-smd",
               ".snd": "audio/basic",
               ".spc": "application/x-pkcs7-certificates",
               ".spl": "application/futuresplash",
               ".spr": "application/x-sprite",
               ".sprite": "application/x-sprite",
               ".sdp": "application/sdp",
               ".spt": "application/x-spt",
               ".src": "application/x-wais-source",
               ".sst": "application/vnd.ms-pkicertstore",
               ".stk": "application/hyperstudio",
               ".stl": "application/vnd.ms-pkistl",
               ".stm": "text/html",
               ".svg": "image/svg+xml",
               ".sv4cpio": "application/x-sv4cpio",
               ".sv4crc": "application/x-sv4crc",
               ".svf": "image/vnd",
               ".svh": "image/svh",
               ".svr": "x-world/x-svr",
               ".swf": "application/x-shockwave-flash",
               ".swfl": "application/x-shockwave-flash",
               ".t": "application/x-troff",
               ".tad": "application/octet-stream",
               ".talk": "text/x-speech",
               ".tar": "application/x-tar",
               ".taz": "application/x-tar",
               ".tbp": "application/x-timbuktu",
               ".tbt": "application/x-timbuktu",
               ".tcl": "application/x-tcl",
               ".tex": "application/x-tex",
               ".texi": "application/x-texinfo",
               ".texinfo": "application/x-texinfo",
               ".tgz": "application/x-compressed",
               ".thm": "application/vnd.eri.thm",
               ".tif": "image/tiff",
               ".tiff": "image/tiff",
               ".tki": "application/x-tkined",
               ".tkined": "application/x-tkined",
               ".toc": "application/toc",
               ".toy": "image/toy",
               ".tr": "application/x-troff",
               ".trk": "x-lml/x-gps",
               ".trm": "application/x-msterminal",
               ".tsi": "audio/tsplayer",
               ".tsp": "application/dsptype",
               ".tsv": "text/tab-separated-values",
               ".ttf": "application/octet-stream",
               ".ttz": "application/t-time",
               ".txt": "text/plain",
               ".uls": "text/iuls",
               ".ult": "audio/x-mod",
               ".ustar": "application/x-ustar",
               ".uu": "application/x-uuencode",
               ".uue": "application/x-uuencode",
               ".vcd": "application/x-cdlink",
               ".vcf": "text/x-vcard",
               ".vdo": "video/vdo",
               ".vib": "audio/vib",
               ".viv": "video/vivo",
               ".vivo": "video/vivo",
               ".vmd": "application/vocaltec-media-desc",
               ".vmf": "application/vocaltec-media-file",
               ".vmi": "application/x-dreamcast-vms-info",
               ".vms": "application/x-dreamcast-vms",
               ".vox": "audio/voxware",
               ".vqe": "audio/x-twinvq-plugin",
               ".vqf": "audio/x-twinvq",
               ".vql": "audio/x-twinvq",
               ".vre": "x-world/x-vream",
               ".vrml": "x-world/x-vrml",
               ".vrt": "x-world/x-vrt",
               ".vrw": "x-world/x-vream",
               ".vts": "workbook/formulaone",
               ".wav": "audio/x-wav",
               ".wax": "audio/x-ms-wax",
               ".wbmp": "image/vnd.wap.wbmp",
               ".wcm": "application/vnd.ms-works",
               ".wdb": "application/vnd.ms-works",
               ".web": "application/vnd.xara",
               ".wi": "image/wavelet",
               ".wis": "application/x-InstallShield",
               ".wks": "application/vnd.ms-works",
               ".wm": "video/x-ms-wm",
               ".wma": "audio/x-ms-wma",
               ".wmd": "application/x-ms-wmd",
               ".wmf": "application/x-msmetafile",
               ".wml": "text/vnd.wap.wml",
               ".wmlc": "application/vnd.wap.wmlc",
               ".wmls": "text/vnd.wap.wmlscript",
               ".wmlsc": "application/vnd.wap.wmlscriptc",
               ".wmlscript": "text/vnd.wap.wmlscript",
               ".wmv": "audio/x-ms-wmv",
               ".wmx": "video/x-ms-wmx",
               ".wmz": "application/x-ms-wmz",
               ".wpng": "image/x-up-wpng",
               ".wps": "application/vnd.ms-works",
               ".wpt": "x-lml/x-gps",
               ".wri": "application/x-mswrite",
               ".wrl": "x-world/x-vrml",
               ".wrz": "x-world/x-vrml",
               ".ws": "text/vnd.wap.wmlscript",
               ".wsc": "application/vnd.wap.wmlscriptc",
               ".wv": "video/wavelet",
               ".wvx": "video/x-ms-wvx",
               ".wxl": "application/x-wxl",
               ".x-gzip": "application/x-gzip",
               ".xar": "application/vnd.xara",
               ".xbm": "image/x-xbitmap",
               ".xdm": "application/x-xdma",
               ".xdma": "application/x-xdma",
               ".xdw": "application/vnd.fujixerox.docuworks",
               ".xht": "application/xhtml+xml",
               ".xhtm": "application/xhtml+xml",
               ".xhtml": "application/xhtml+xml",
               ".xla": "application/vnd.ms-excel",
               ".xlc": "application/vnd.ms-excel",
               ".xll": "application/x-excel",
               ".xlm": "application/vnd.ms-excel",
               ".xls": "application/vnd.ms-excel",
               ".xlsx": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
               ".xlt": "application/vnd.ms-excel",
               ".xlw": "application/vnd.ms-excel",
               ".xm": "audio/x-mod",
               ".xmz": "audio/x-mod",
               ".xpm": "image/x-xpixmap",
               ".xwd": "image/x-xwindowdump",
               ".zip": "application/zip",
               }
