"10001": "web目录下未找到对应的yml配置文件。可以创建一个对应域名的yml配置到web目录下，或者在config.yml中直接开启‘自动主站’或‘自动泛站’功能。"
"10002": "当前网站配置模板为随机抽取现有目标站的from.yml，目标站数量小等于5不会自动创建网站配置。请新开主站直至创建target目标站数量大于5，则可以自动开站，或者改‘主/泛站配置模板’为‘config/base.yml’，直接自动生成配置。"
"10003": "yml配置文件中的‘模板’非路径或路径不存在。请写上正确的模板路径，或者直接将‘模板’值改为‘自动’。"